# Generated by Django 2.2.4 on 2020-04-18 12:02

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default/user.svg', null=True, upload_to=users.models.user_photos_dir),
        ),
    ]
