# Generated by Django 2.2.4 on 2019-09-18 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('akaApp', '0002_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
