# Generated by Django 2.2.4 on 2020-04-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akaApp', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_blog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='is_news',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='is_q',
            field=models.BooleanField(default=False),
        ),
    ]
