# Generated by Django 2.2.4 on 2019-11-25 16:40

from django.db import migrations, models
import uploads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=uploads.models.upload_path)),
            ],
        ),
    ]
